import { Georama } from "next/font/google";

//CSS:
import "bootstrap/dist/css/bootstrap.min.css";
import "../css/globals.css";

const inter = Georama({ subsets: ["latin"] });

export const metadata = {
  title: "Mi Dalefon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
